-- 접속자 확인
SELECT USER FROM DUAL;

-- SYSTEM 계정
DROP USER ERP_FINAL_JSP;

-- ERP 사용자 생성하기
CREATE USER ERP_FINAL_JSP IDENTIFIED BY rootroot;

-- Grant 명령으로 접속, 사용 권한 주기
GRANT CONNECT, RESOURCE, CREATE SYNONYM, CREATE VIEW TO ERP_FINAL_JSP;


-- 계정 확인
SELECT USERNAME, DEFAULT_TABLESPACE, PROFILE, AUTHENTICATION_TYPE
  FROM DBA_USERS
 WHERE USERNAME = 'ERP_JSP_EXAM';
 